services:
  client:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    image: client:v0.0.1
    container_name: client
    restart: unless-stopped
    user: "user:group"

  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    image: server:v0.0.1
    container_name: server
    ports:
      - "8080:8080"
      - "9090"
    restart: unless-stopped
    user: "user:group"

  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/opt/bitnami/prometheus/data
      - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    environment:
      - PROMETHEUS_CONFIG_FILE=/opt/bitnami/prometheus/conf/prometheus.yml
    depends_on:
      - server
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    restart: unless-stopped

  # otel-selector:
  #   image: otel/opentelemetry-collector:0.123.0
  #   container_name: otel-selector
  #   ports:
  #     - "4318"

  # netshoot:
  #   image: nicolaka/netshoot
  #   container_name: netshoot
  #   command:
  #     - "tail"
  #     - "-f"
  #     - "/dev/null"
volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

